### PR TITLE
Update travis example

### PR DESCRIPTION
**Pull request by SethMMorton**
This PR is intended to validate the proposed changes in https://github.com/joerick/cibuildwheel/issues/223.

### CODE REVIEW

**Comment by SethMMorton** [comment]
For some reason, GitHub is not showing the Travis-CI builds. Here is the link to the build that corresponds to the last commit:

https://travis-ci.com/SethMMorton/cibuildwheel-autopypi-example/builds/137960086

**Comment by joerick** [comment]
Good stuff. I didn't realise the `script` phase continued even on a failure. 

From Travis docs:
> When one of the build commands returns a non-zero exit code, the Travis CI build runs the subsequent commands as well and accumulates the build result.

Thanks for catching that!

**Comment by joerick** [comment]
With Windows Travis building, we can simplify by removing Appveyor from this example too. I'll disable the webhook, could you remove the appveyor config file?

**Comment by SethMMorton** [comment]
I can remove the Appveyor config if you want, but I was actually going to suggest the opposite. Since the `cibuildwheel` docs have examples for many different CI services, it might make sense for this repo to be connected to each of those services to test the examples in the documentation. Though, since I only use TravisCI I am not really volunteering to add all the examples.

**Comment by SethMMorton** [comment]
Interesting... the example works for me (my tests were running on travis-ci.com) but fail for you (you are using travis-ci.org). That is disappointing.  I will update the "language" to be "shell" since that works for both.

**Pull request merged**
